#!/bin/bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
bk_dir=$dir.bk

rm -rf $bk_dir
mkdir -p $bk_dir

function backup {
  if [ -e ~/.$1 ]
  then
    echo "backing up .$1"
    mv ~/.$1 $dir.bk/$(dirname $1)
  fi
}

backup vim
echo 'installing vim config'
ln -s $dir/vim ~/.vim
backup config/nvim
echo 'linking neovim config'
ln -s $dir/vim ~/.config/nvim
echo 'linking zsh theme'
ln -fs $dir/oh-my-zsh/custom/themes/* ~/.oh-my-zsh/custom/themes
backup tmux.conf
echo 'linking tmux config'
ln -s $dir/tmux.conf ~/.tmux.conf
