#!/bin/bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
bk_dir=$dir.bk$(date +%Y%m%d-%H%M%S)

mkdir -p $bk_dir

function backup {
  if [ -e ~/.$1 ]
  then
    echo "backing up .$1"
    mkdir -p $bk_dir/$(dirname $1)
    mv ~/.$1 $bk_dir/$(dirname $1)
  fi
}

backup vim
echo 'installing vim config'
ln -s $dir/vim ~/.vim
backup config/nvim
echo 'linking neovim config'
ln -s $dir/vim ~/.config/nvim
echo 'linking zsh theme'
ln -fs $dir/oh-my-zsh/custom/themes/* ~/.oh-my-zsh/custom/themes
backup tmux.conf
echo 'linking tmux config'
ln -fs $dir/tmux.conf ~/.tmux.conf
echo 'linking agignore'
ln -fs $dir/agignore ~/.agignore

backup zshrc
echo 'linking zshrc'
ln -fs $dir/zshrc ~/.zshrc
backup oh-my-zsh/custom/pure
echo 'linking zsh customized pure theme'
ln -fs $dir/oh-my-zsh/custom/pure ~/.oh-my-zsh/custom/pure
mkdir -p ~/.oh-my-zsh/functions
ln -fs $dir/oh-my-zsh/custom/pure/pure.zsh ~/.oh-my-zsh/functions/prompt_pure_setup
ln -fs $dir/oh-my-zsh/custom/pure/async.zsh ~/.oh-my-zsh/functions/async
