set guifont=Menlo:h12
highlight Cursor guifg=white guibg=yellow guifg=black
highlight iCursor guifg=white guibg=yellow guifg=black
set guicursor+=n-v-c:blinkon0
set guicursor+=i-ci:ver25-Cursor/lCursor-blinkon0
set linespace=2
