set nocompatible

if has('syntax')
  syntax enable
endif

set autoindent
set backspace=indent,eol,start
set complete-=i
set smarttab
set incsearch
set tabstop=2
set shiftwidth=2
set expandtab
set number
colorscheme Tomorrow-Night-Eighties
set cursorline
set wildmenu
set noswapfile
